Setting pipefail

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -119,11 +119,24 @@ runs:
       working-directory: ${{ inputs.working-directory }}
       shell: bash
       run: |
-        flutter build ipa -v --flavor ${{ env.FLAVOR }} --target lib/flavors/main_${{ env.FLAVOR }}.dart --export-options-plist=ios/flavors/${{ env.FLAVOR }}/ExportOptions.plist
+        set -o pipefail && flutter build ipa -v --flavor ${{ env.FLAVOR }} --target lib/flavors/main_${{ env.FLAVOR }}.dart --export-options-plist=ios/flavors/${{ env.FLAVOR }}/ExportOptions.plist
 
     - name: Build iOS artifact without flavor
       if: ${{ env.USE_FLAVOR == 'false' }}
       shell: bash
       working-directory: ${{ inputs.working-directory }}
       run: |
-        flutter build ipa -v --export-options-plist=ios/ExportOptions.plist
+        set -o pipefail && flutter build ipa -v --export-options-plist=ios/ExportOptions.plist
+    
+    - name: Checking if IPA export succeeded
+      shell: bash
+      working-directory: ${{ inputs.working-directory }}
+      run: |
+        IPA_PATH="build/ios/ipa"
+        ls $IPA_PATH
+        if [ ! -f "$IPA_PATH" ]; then
+          echo "❌ IPA export failed: $IPA_PATH not found"
+          exit 1
+        else
+          echo "✅ IPA export succeeded: $IPA_PATH found"
+        fi
